version = 5.6.0
archive_dir = /etc/letsencrypt/archive/abokamel.prognil.com
cert = /etc/letsencrypt/live/abokamel.prognil.com/cert.pem
privkey = /etc/letsencrypt/live/abokamel.prognil.com/privkey.pem
chain = /etc/letsencrypt/live/abokamel.prognil.com/chain.pem
fullchain = /etc/letsencrypt/live/abokamel.prognil.com/fullchain.pem
[renewalparams]
account = 117e1290b8d15c09ac0974baaccc8775
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
abokamel.prognil.com = /var/www/certbot
