using AboKamel.Core.Enums;
using Capsula.Domain.Entities.Carts;
using Capsula.Domain.Entities.Orders;
using Services.Application.Mappings;

namespace AboKamel.Application.Mappings.Mobile.Orders;

public static class OrderMapping
{
    public static void AddOrderMapping(this MappingProfiles map)
    {
        // Cart → Order
        map.CreateMap<Cart, Order>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // Usually generated by DB
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => OrderStatus.Pending))
            .ForMember(dest => dest.ArrivalDate, opt => opt.Ignore()) // You may set it elsewhere
            .ForMember(dest => dest.Items, opt => opt.MapFrom(src => src.Items))
            .ForMember(dest => dest.CustomerId, opt => opt.MapFrom(src => src.CustomerId))
            .ForMember(dest => dest.Customer, opt => opt.MapFrom(src => src.Customer));

        // CartItem → OrderItem
        map.CreateMap<CartItem, OrderItem>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.OrderId, opt => opt.Ignore()) // Will be set after order creation
            .ForMember(dest => dest.Order, opt => opt.Ignore())
            .ForMember(dest => dest.ProductId, opt => opt.MapFrom(src => src.ProductId))
            .ForMember(dest => dest.Product, opt => opt.MapFrom(src => src.Product))
            .ForMember(dest => dest.Quantity, opt => opt.MapFrom(src => src.Quantity))
            .ForMember(dest => dest.Price, opt => opt.MapFrom(src => src.ProductSellingUnit.Price))
            .ForMember(dest => dest.SellingUnitId, opt => opt.MapFrom(src => src.ProductSellingUnit.SellingUnitId));
    }
}
